source 'https://rubygems.org'
ruby '2.3.1'
gem 'rails', '4.2.6'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'compass-rails'
gem 'chosen-rails'
gem 'unicorn'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'autoprefixer-rails'
gem 'public_activity'
gem 'omniauth-facebook'
gem 'will_paginate', github: 'jonatack/will_paginate'
gem 'simple_form'
gem 'ransack'
gem 'faker'
gem 'redcarpet'
gem 'font-awesome-sass'

group :development, :test do
  gem 'byebug'
  gem 'letter_opener'
  gem 'dotenv-rails'
end
gem 'bootstrap-sass'
gem 'devise'
gem 'haml-rails'
gem 'pry-rails'
gem 'pry-byebug'
#gem 'high_voltage'
gem 'pundit'
gem 'therubyracer', :platform=>:ruby
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'binding_of_caller'
end

group :test do
  gem 'minitest-utils'
  gem 'database_cleaner'
end
